-- MySQL Script generated by MySQL Workbench
-- Wed Jan 12 23:23:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz_practice_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quiz_practice_db` ;

-- -----------------------------------------------------
-- Schema quiz_practice_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz_practice_db` ;
USE `quiz_practice_db` ;

-- -----------------------------------------------------
-- Table `quiz_practice_db`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`account` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `username` NVARCHAR(45) NOT NULL,
  `password` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `quiz_practice_db`.`account_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`account_profile` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`account_profile` (
  `account_id` INT NOT NULL,
  `account_email` NVARCHAR(45) NOT NULL,
  `account_phone` NVARCHAR(45) NOT NULL,
  `account_fullname` NVARCHAR(45) NOT NULL,
  `account_dob` DATETIME NOT NULL,
  `address` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_account_account_profile_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `quiz_practice_db`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_practice_db`.`account_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`account_role` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`account_role` (
  `account_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `role_id`),
  CONSTRAINT `fk_account_account_role_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `quiz_practice_db`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_account_role_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `quiz_practice_db`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_practice_db`.`function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`function` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`function` (
  `function_id` INT NOT NULL AUTO_INCREMENT,
  `function_name` NVARCHAR(45) NOT NULL,
  `function_url` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`function_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_practice_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`role` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_type` NVARCHAR(45) NOT NULL,
  `role_name` NVARCHAR(45) NOT NULL,
  `role_description` NVARCHAR(200) NOT NULL,
  `role_value` NVARCHAR(45) NOT NULL,
  `role_active` BIT NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_practice_db`.`role_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_practice_db`.`role_function` ;

CREATE TABLE IF NOT EXISTS `quiz_practice_db`.`role_function` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `function_id` INT NOT NULL,
  `function_active` BIT NOT NULL,
  PRIMARY KEY (`role_id`, `function_id`),
  CONSTRAINT `FK_role_role_function_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `quiz_practice_db`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_function_role_function_function_id`
    FOREIGN KEY (`function_id`)
    REFERENCES `quiz_practice_db`.`function` (`function_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
